env:
  test_host: https://api.test.utown.io:32080
  beta_host: https://api.beta.utown.io
  prod_host: https://api.utown.io
  id_host: https://api.jagat.io
spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          url: jdbc:mysql://172.16.2.4:3307/utown_user?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver # 3.2.0开始支持SPI可省略此配置
#        slave_1:
#          url: jdbc:mysql://localhost:3306/test01?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#          username: root
#          password: 123456
#          driver-class-name: com.mysql.cj.jdbc.Driver
        #        slave_2:
        #          url: ENC(xxxxx) # 内置加密,使用请查看详细文档
        #          username: ENC(xxxxx)
        #          password: ENC(xxxxx)
        #          driver-class-name: com.mysql.cj.jdbc.Driver
        #......省略
        #以上会配置一个默认库master，一个组slave下有两个子库slave_1,slave_2